version: '2.1'

services:
  smoke-tests:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/cmc/smoke-tests:${SMOKE_TESTS_VERSION:-latest}
    environment:
      - WEB_DRIVER_HOST=remote-webdriver
      - APP_URL
      - TEST_USERNAME
      - TEST_PASSWORD
      - http_proxy=
      - https_proxy=
      - no_proxy=
    depends_on:
      - remote-webdriver
    volumes:
      - ./output:/usr/src/app/output
  remote-webdriver:
    image: selenium/standalone-chrome:3.5
